server:
  port: 8050
spring:     #定义springmvc视图解析器
  thymeleaf:
    cache: false
    prefix: classpath:/templates/views/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**-
    #  mvc:
    #    view:

    #      prefix: /WEB-INF/views/
    #      suffix: .html
  datasource:
    test1:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      jdbc-url: jdbc:sqlserver://oa.tjasset.com:19995;DatabaseName=tjasset
      username: sa
      password: TJasset@123
    test2:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      jdbc-url: jdbc:sqlserver://192.168.2.2:1433;DatabaseName=UFDATA_006_2015
#      jdbc-url: jdbc:sqlserver://192.168.1.10:1433;DatabaseName=UFDATA_888_2016
      username: sa
      password: sasa
#     password: asset10010

#mybatis-plush配置
mybatis-plus:
  type-aliases-package: com.system.pojo.*
  mapper-locations: classpath:/mybatis/mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.system.mapper: debug

