package com.system.mapper.send;

import com.system.pojo.send.ContractMain;
import com.system.pojo.send.Formmain0031;

import java.math.BigDecimal;
import java.util.List;

public interface Formmain0031Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table formmain_0031
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table formmain_0031
     *
     * @mbggenerated
     */
    int insert(Formmain0031 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table formmain_0031
     *
     * @mbggenerated
     */
    int insertSelective(Formmain0031 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table formmain_0031
     *
     * @mbggenerated
     */
    Formmain0031 selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table formmain_0031
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Formmain0031 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table formmain_0031
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Formmain0031 record);

    List<ContractMain> selectAll();
}