package com.system.pojo.send;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * 停用
 */
public class FormSon0032 implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column formson_0032.ID
     *
     * @mbggenerated
     */
    private BigDecimal id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column formson_0032.formmain_id
     *
     * @mbggenerated
     */
    private BigDecimal formmainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column formson_0032.sort
     *
     * @mbggenerated
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column formson_0032.field0006
     *
     * @mbggenerated
     */
    private BigDecimal field0006;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column formson_0032.field0008
     *
     * @mbggenerated
     */
    private String field0008;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column formson_0032.field0009
     *
     * @mbggenerated
     */
    private String field0009;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column formson_0032.field0010
     *
     * @mbggenerated
     */
    private BigDecimal field0010;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column formson_0032.field0020
     *
     * @mbggenerated
     */
    private String field0020;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column formson_0032.field0024
     *
     * @mbggenerated
     */
    private String field0024;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column formson_0032.field0025
     *
     * @mbggenerated
     */
    private String field0025;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column formson_0032.field0026
     *
     * @mbggenerated
     */
    private String field0026;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column formson_0032.field0027
     *
     * @mbggenerated
     */
    private String field0027;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column formson_0032.field0028
     *
     * @mbggenerated
     */
    private String field0028;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column formson_0032.field0029
     *
     * @mbggenerated
     */
    private String field0029;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column formson_0032.field0030
     *
     * @mbggenerated
     */
    private String field0030;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column formson_0032.field0031
     *
     * @mbggenerated
     */
    private String field0031;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column formson_0032.field0032
     *
     * @mbggenerated
     */
    private Date field0032;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column formson_0032.field0033
     *
     * @mbggenerated
     */
    private BigDecimal field0033;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column formson_0032.field0034
     *
     * @mbggenerated
     */
    private BigDecimal field0034;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column formson_0032.field0054
     *
     * @mbggenerated
     */
    private String field0054;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table formson_0032
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column formson_0032.ID
     *
     * @return the value of formson_0032.ID
     *
     * @mbggenerated
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column formson_0032.ID
     *
     * @param id the value for formson_0032.ID
     *
     * @mbggenerated
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column formson_0032.formmain_id
     *
     * @return the value of formson_0032.formmain_id
     *
     * @mbggenerated
     */
    public BigDecimal getFormmainId() {
        return formmainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column formson_0032.formmain_id
     *
     * @param formmainId the value for formson_0032.formmain_id
     *
     * @mbggenerated
     */
    public void setFormmainId(BigDecimal formmainId) {
        this.formmainId = formmainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column formson_0032.sort
     *
     * @return the value of formson_0032.sort
     *
     * @mbggenerated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column formson_0032.sort
     *
     * @param sort the value for formson_0032.sort
     *
     * @mbggenerated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column formson_0032.field0006
     *
     * @return the value of formson_0032.field0006
     *
     * @mbggenerated
     */
    public BigDecimal getField0006() {
        return field0006;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column formson_0032.field0006
     *
     * @param field0006 the value for formson_0032.field0006
     *
     * @mbggenerated
     */
    public void setField0006(BigDecimal field0006) {
        this.field0006 = field0006;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column formson_0032.field0008
     *
     * @return the value of formson_0032.field0008
     *
     * @mbggenerated
     */
    public String getField0008() {
        return field0008;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column formson_0032.field0008
     *
     * @param field0008 the value for formson_0032.field0008
     *
     * @mbggenerated
     */
    public void setField0008(String field0008) {
        this.field0008 = field0008 == null ? null : field0008.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column formson_0032.field0009
     *
     * @return the value of formson_0032.field0009
     *
     * @mbggenerated
     */
    public String getField0009() {
        return field0009;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column formson_0032.field0009
     *
     * @param field0009 the value for formson_0032.field0009
     *
     * @mbggenerated
     */
    public void setField0009(String field0009) {
        this.field0009 = field0009 == null ? null : field0009.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column formson_0032.field0010
     *
     * @return the value of formson_0032.field0010
     *
     * @mbggenerated
     */
    public BigDecimal getField0010() {
        return field0010;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column formson_0032.field0010
     *
     * @param field0010 the value for formson_0032.field0010
     *
     * @mbggenerated
     */
    public void setField0010(BigDecimal field0010) {
        this.field0010 = field0010;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column formson_0032.field0020
     *
     * @return the value of formson_0032.field0020
     *
     * @mbggenerated
     */
    public String getField0020() {
        return field0020;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column formson_0032.field0020
     *
     * @param field0020 the value for formson_0032.field0020
     *
     * @mbggenerated
     */
    public void setField0020(String field0020) {
        this.field0020 = field0020 == null ? null : field0020.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column formson_0032.field0024
     *
     * @return the value of formson_0032.field0024
     *
     * @mbggenerated
     */
    public String getField0024() {
        return field0024;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column formson_0032.field0024
     *
     * @param field0024 the value for formson_0032.field0024
     *
     * @mbggenerated
     */
    public void setField0024(String field0024) {
        this.field0024 = field0024 == null ? null : field0024.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column formson_0032.field0025
     *
     * @return the value of formson_0032.field0025
     *
     * @mbggenerated
     */
    public String getField0025() {
        return field0025;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column formson_0032.field0025
     *
     * @param field0025 the value for formson_0032.field0025
     *
     * @mbggenerated
     */
    public void setField0025(String field0025) {
        this.field0025 = field0025 == null ? null : field0025.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column formson_0032.field0026
     *
     * @return the value of formson_0032.field0026
     *
     * @mbggenerated
     */
    public String getField0026() {
        return field0026;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column formson_0032.field0026
     *
     * @param field0026 the value for formson_0032.field0026
     *
     * @mbggenerated
     */
    public void setField0026(String field0026) {
        this.field0026 = field0026 == null ? null : field0026.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column formson_0032.field0027
     *
     * @return the value of formson_0032.field0027
     *
     * @mbggenerated
     */
    public String getField0027() {
        return field0027;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column formson_0032.field0027
     *
     * @param field0027 the value for formson_0032.field0027
     *
     * @mbggenerated
     */
    public void setField0027(String field0027) {
        this.field0027 = field0027 == null ? null : field0027.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column formson_0032.field0028
     *
     * @return the value of formson_0032.field0028
     *
     * @mbggenerated
     */
    public String getField0028() {
        return field0028;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column formson_0032.field0028
     *
     * @param field0028 the value for formson_0032.field0028
     *
     * @mbggenerated
     */
    public void setField0028(String field0028) {
        this.field0028 = field0028 == null ? null : field0028.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column formson_0032.field0029
     *
     * @return the value of formson_0032.field0029
     *
     * @mbggenerated
     */
    public String getField0029() {
        return field0029;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column formson_0032.field0029
     *
     * @param field0029 the value for formson_0032.field0029
     *
     * @mbggenerated
     */
    public void setField0029(String field0029) {
        this.field0029 = field0029 == null ? null : field0029.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column formson_0032.field0030
     *
     * @return the value of formson_0032.field0030
     *
     * @mbggenerated
     */
    public String getField0030() {
        return field0030;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column formson_0032.field0030
     *
     * @param field0030 the value for formson_0032.field0030
     *
     * @mbggenerated
     */
    public void setField0030(String field0030) {
        this.field0030 = field0030 == null ? null : field0030.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column formson_0032.field0031
     *
     * @return the value of formson_0032.field0031
     *
     * @mbggenerated
     */
    public String getField0031() {
        return field0031;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column formson_0032.field0031
     *
     * @param field0031 the value for formson_0032.field0031
     *
     * @mbggenerated
     */
    public void setField0031(String field0031) {
        this.field0031 = field0031 == null ? null : field0031.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column formson_0032.field0032
     *
     * @return the value of formson_0032.field0032
     *
     * @mbggenerated
     */
    public Date getField0032() {
        return field0032;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column formson_0032.field0032
     *
     * @param field0032 the value for formson_0032.field0032
     *
     * @mbggenerated
     */
    public void setField0032(Date field0032) {
        this.field0032 = field0032;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column formson_0032.field0033
     *
     * @return the value of formson_0032.field0033
     *
     * @mbggenerated
     */
    public BigDecimal getField0033() {
        return field0033;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column formson_0032.field0033
     *
     * @param field0033 the value for formson_0032.field0033
     *
     * @mbggenerated
     */
    public void setField0033(BigDecimal field0033) {
        this.field0033 = field0033;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column formson_0032.field0034
     *
     * @return the value of formson_0032.field0034
     *
     * @mbggenerated
     */
    public BigDecimal getField0034() {
        return field0034;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column formson_0032.field0034
     *
     * @param field0034 the value for formson_0032.field0034
     *
     * @mbggenerated
     */
    public void setField0034(BigDecimal field0034) {
        this.field0034 = field0034;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column formson_0032.field0054
     *
     * @return the value of formson_0032.field0054
     *
     * @mbggenerated
     */
    public String getField0054() {
        return field0054;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column formson_0032.field0054
     *
     * @param field0054 the value for formson_0032.field0054
     *
     * @mbggenerated
     */
    public void setField0054(String field0054) {
        this.field0054 = field0054 == null ? null : field0054.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table formson_0032
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", formmainId=").append(formmainId);
        sb.append(", sort=").append(sort);
        sb.append(", field0006=").append(field0006);
        sb.append(", field0008=").append(field0008);
        sb.append(", field0009=").append(field0009);
        sb.append(", field0010=").append(field0010);
        sb.append(", field0020=").append(field0020);
        sb.append(", field0024=").append(field0024);
        sb.append(", field0025=").append(field0025);
        sb.append(", field0026=").append(field0026);
        sb.append(", field0027=").append(field0027);
        sb.append(", field0028=").append(field0028);
        sb.append(", field0029=").append(field0029);
        sb.append(", field0030=").append(field0030);
        sb.append(", field0031=").append(field0031);
        sb.append(", field0032=").append(field0032);
        sb.append(", field0033=").append(field0033);
        sb.append(", field0034=").append(field0034);
        sb.append(", field0054=").append(field0054);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}